import { baseSlice } from '../reducers';
export const {
  addMinutes,
  setViewport,
  setDefaultViewport,
  setTimeStamp,
  setTime,
  increaseTime,
  decreaseTime,
  setLeading,
  setTrailing,
  setFrameTimestamp,
  setMovesBase,
  setDepotsBase,
  setLocationData,
  setLocationDataOption,
  setAnimatePause,
  setAnimateReverse,
  setSecPerHour,
  setMultiplySpeed,
  setClicked,
  setRoutePaths,
  setDefaultPitch,
  setMovesOptionFunc,
  setDepotsOptionFunc,
  setExtractedDataFunc,
  setLinemapData,
  setLoading,
  setInputFilename,
  updateMovesBase,
  setNoLoop,
  setInitialViewChange,
  setIconGradationChange,
  setTimeBegin,
  setTimeLength,
  addMovesBaseData,
} = baseSlice.actions
