'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var ADDMINUTES = exports.ADDMINUTES = 'ADDMINUTES';
var INCREASETIME = exports.INCREASETIME = 'INCREASETIME';
var DECREASETIME = exports.DECREASETIME = 'DECREASETIME';
var SETFRAMETIMESTAMP = exports.SETFRAMETIMESTAMP = 'SETFRAMETIMESTAMP';
var SETTIMESTAMP = exports.SETTIMESTAMP = 'SETTIMESTAMP';
var SETTIME = exports.SETTIME = 'SETTIME';
var SETLEADING = exports.SETLEADING = 'SETLEADING';
var SETTRAILING = exports.SETTRAILING = 'SETTRAILING';
var SETVIEWPORT = exports.SETVIEWPORT = 'SETVIEWPORT';
var SETLIGHTSETTINGS = exports.SETLIGHTSETTINGS = 'SETLIGHTSETTINGS';
var SETMOVESBASE = exports.SETMOVESBASE = 'SETMOVESBASE';
var SETDEPOTSBASE = exports.SETDEPOTSBASE = 'SETDEPOTSBASE';
var SETANIMATEPAUSE = exports.SETANIMATEPAUSE = 'SETANIMATEPAUSE';
var SETANIMATEREVERSE = exports.SETANIMATEREVERSE = 'SETANIMATEREVERSE';
var SETSECPERHOUR = exports.SETSECPERHOUR = 'SETSECPERHOUR';
var SETCLICKED = exports.SETCLICKED = 'SETCLICKED';
var SETROUTEPATHS = exports.SETROUTEPATHS = 'SETROUTEPATHS';
var SETDEFAULTZOOM = exports.SETDEFAULTZOOM = 'SETDEFAULTZOOM';
var SETDEFAULTPITCH = exports.SETDEFAULTPITCH = 'SETDEFAULTPITCH';
var SETMOVESOPTIONFUNC = exports.SETMOVESOPTIONFUNC = 'SETMOVESOPTIONFUNC';
var SETDEPOTSOPTIONFUNC = exports.SETDEPOTSOPTIONFUNC = 'SETDEPOTSOPTIONFUNC';
var SETNONMAPVIEW = exports.SETNONMAPVIEW = 'SETNONMAPVIEW';
var SETLINEMAPDATA = exports.SETLINEMAPDATA = 'SETLINEMAPDATA';