export declare const FETCHDATALIST: any;
export declare const FETCHDATABYANSWER: any;
export declare const FETCHBUSSTOPCSV: any;
export declare const FETCHBUSSTOPROUTESJSON: any;
export declare const FETCHROUTESJSON: any;
export declare const FETCHBUSSTOPSOPTION: any;
export declare const INITIALIZEFETCH: any;
export declare const SETUPFETCH: any;
export declare const UPDATEROUTE: any;
export declare const UPDATERAINFALL: any;
/** reducer * */
export declare const SETDELAYHEIGHT = "SETDELAYHEIGHT";
export declare const SETSCALEELEVATION = "SETSCALEELEVATION";
export declare const SETCELLSIZE = "SETCELLSIZE";
export declare const SETXBANDFNAME = "SETXBANDFNAME";
export declare const SETDELAYRANGE = "SETDELAYRANGE";
export declare const SETBSOPTFNAME = "SETBSOPTFNAME";
export declare const SETSELECTEDBUSSTOP = "SETSELECTEDBUSSTOP";
export declare const SETSELECTEDBUS = "SETSELECTEDBUS";
export declare const SETANSWERS = "SETANSWERS";
export declare const SETANSWER = "SETANSWER";
export declare const SETHOVERED = "SETHOVERED";
export declare const SETBUSOPTION = "SETBUSOPTION";
export declare const SETBUSMOVESBASEDIC = "SETBUSMOVESBASEDIC";
export declare const SETROUTESDATA = "SETROUTESDATA";
export declare const SETBUSTRIPSCSV = "SETBUSTRIPSCSV";
export declare const SETBUSSTOPSCSV = "SETBUSSTOPSCSV";
export declare const SETBUSROUTES = "SETBUSROUTES";
export declare const SETBUSTRIPINDEX = "SETBUSTRIPINDEX";
export declare const SETARCHBASE = "SETARCHBASE";
export declare const SETRAINFALL = "SETRAINFALL";
