// @flow

export const ADDMINUTES = 'ADDMINUTES';
export const INCREASETIME = 'INCREASETIME';
export const DECREASETIME = 'DECREASETIME';
export const SETFRAMETIMESTAMP = 'SETFRAMETIMESTAMP';
export const SETTIMESTAMP = 'SETTIMESTAMP';
export const SETTIME = 'SETTIME';
export const SETLEADING = 'SETLEADING';
export const SETTRAILING = 'SETTRAILING';
export const SETVIEWPORT = 'SETVIEWPORT';
export const SETLIGHTSETTINGS = 'SETLIGHTSETTINGS';
export const SETMOVESBASE = 'SETMOVESBASE';
export const SETDEPOTSBASE = 'SETDEPOTSBASE';
export const SETANIMATEPAUSE = 'SETANIMATEPAUSE';
export const SETANIMATEREVERSE = 'SETANIMATEREVERSE';
export const SETSECPERHOUR = 'SETSECPERHOUR';
export const SETCLICKED = 'SETCLICKED';
export const SETROUTEPATHS = 'SETROUTEPATHS';
export const SETDEFAULTZOOM = 'SETDEFAULTZOOM';
export const SETDEFAULTPITCH = 'SETDEFAULTPITCH';
export const SETMOVESOPTIONFUNC = 'SETMOVESOPTIONFUNC';
export const SETDEPOTSOPTIONFUNC = 'SETDEPOTSOPTIONFUNC';
export const SETNONMAPVIEW = 'SETNONMAPVIEW';
export const SETLINEMAPDATA = 'SETLINEMAPDATA';

