import { LayerProps, CompositeLayer, PolygonLayer } from 'deck.gl';
import { LightSettings } from '../../types';
interface Props extends LayerProps {
    filled?: boolean;
    stroked?: boolean;
    extruded?: boolean;
    wireframe?: boolean;
    elevationScale?: number;
    lineWidthScale?: boolean;
    lineWidthMinPixels?: number;
    lineWidthMaxPixels?: number;
    lineJointRounded?: boolean;
    lineMiterLimit?: number;
    lineDashJustified?: boolean;
    lightSettings: LightSettings;
    getPolygon?: (x: any) => number[];
    getFillColor?: (x: any) => number[] | number[];
    getLineColor?: (x: any) => number[] | number[];
    getLineWidth?: (x: any) => number | number;
    getElevation?: (x: any) => number | number;
    cellSize?: number;
    getPosition?: (x: any) => number[];
    getColor?: (x: any) => number[] | number[];
    getVertexAngle?: (x: any) => number;
}
export default class PolygonIconLayer extends CompositeLayer<Props> {
    constructor(props: Props);
    static defaultProps: {
        visible: boolean;
        opacity: number;
        pickable: boolean;
        filled: boolean;
        stroked: boolean;
        extruded: boolean;
        wireframe: boolean;
        elevationScale: number;
        lineWidthScale: number;
        lineWidthMinPixels: number;
        lineWidthMaxPixels: number;
        lineJointRounded: boolean;
        lineMiterLimit: number;
        lineDashJustified: boolean;
        lightSettings: {};
        getLineWidth: number;
        getElevation: number;
        cellSize: number;
        getPosition: (x: any) => any;
        getColor: number[];
        getVertexAngle: () => number;
    };
    static layerName: string;
    renderLayers(): PolygonLayer<{
        id: string;
        data: any[];
        visible: boolean;
        opacity: number;
        pickable: boolean;
        filled: boolean;
        stroked: boolean;
        extruded: boolean;
        wireframe: boolean;
        elevationScale: number;
        lineWidthScale: boolean;
        lineWidthMinPixels: number;
        lineWidthMaxPixels: number;
        lineJointRounded: boolean;
        lineMiterLimit: number;
        lineDashJustified: boolean;
        lightSettings: LightSettings;
        getPolygon: (x: any) => any;
        getFillColor: (x: any) => number[];
        getLineColor: (x: any) => number[];
        getLineWidth: (x: any) => number;
        getElevation: (x: any) => number;
    }, {}>[];
}
export {};
