import { BasedProps as Props, Viewport, Movesbase, MovesbaseFile, Depotsbase, GetMovesOptionFunc, GetDepotsOptionFunc, ClickedObject, RoutePaths, LineMapData } from '../types';
export declare const addMinutes: import("typescript-fsa").ActionCreator<number>;
export declare const increaseTime: import("typescript-fsa").ActionCreator<Props>;
export declare const decreaseTime: import("typescript-fsa").ActionCreator<Props>;
export declare const setFrameTimestamp: import("typescript-fsa").ActionCreator<Props>;
export declare const setTimeStamp: import("typescript-fsa").ActionCreator<Props>;
export declare const setTime: import("typescript-fsa").ActionCreator<number>;
export declare const setLeading: import("typescript-fsa").ActionCreator<number>;
export declare const setTrailing: import("typescript-fsa").ActionCreator<number>;
export declare const setViewport: import("typescript-fsa").ActionCreator<Viewport>;
export declare const setDefaultViewport: import("typescript-fsa").ActionCreator<void | {
    defaultZoom?: number;
    defaultPitch?: number;
}>;
export declare const setMovesBase: import("typescript-fsa").ActionCreator<MovesbaseFile | Movesbase[]>;
export declare const setDepotsBase: import("typescript-fsa").ActionCreator<Depotsbase[]>;
export declare const setAnimatePause: import("typescript-fsa").ActionCreator<boolean>;
export declare const setAnimateReverse: import("typescript-fsa").ActionCreator<boolean>;
export declare const setSecPerHour: import("typescript-fsa").ActionCreator<number>;
export declare const setClicked: import("typescript-fsa").ActionCreator<ClickedObject[]>;
export declare const setRoutePaths: import("typescript-fsa").ActionCreator<RoutePaths[]>;
export declare const setDefaultZoom: import("typescript-fsa").ActionCreator<number>;
export declare const setDefaultPitch: import("typescript-fsa").ActionCreator<number>;
export declare const setMovesOptionFunc: import("typescript-fsa").ActionCreator<GetMovesOptionFunc>;
export declare const setDepotsOptionFunc: import("typescript-fsa").ActionCreator<GetDepotsOptionFunc>;
export declare const setLinemapData: import("typescript-fsa").ActionCreator<LineMapData[]>;
export declare const setLoading: import("typescript-fsa").ActionCreator<boolean>;
export declare const setInputFilename: import("typescript-fsa").ActionCreator<Object>;
export declare const updateMovesBase: import("typescript-fsa").ActionCreator<MovesbaseFile | Movesbase[]>;
export declare const setNoLoop: import("typescript-fsa").ActionCreator<boolean>;
export declare const setInitialViewChange: import("typescript-fsa").ActionCreator<boolean>;
export declare const setIconGradationChange: import("typescript-fsa").ActionCreator<boolean>;
export declare const setTimeBegin: import("typescript-fsa").ActionCreator<number>;
export declare const setTimeLength: import("typescript-fsa").ActionCreator<number>;
export declare const addMovesBaseData: import("typescript-fsa").ActionCreator<Movesbase[]>;
