import { LayerProps, CompositeLayer, ScatterplotLayer, ScenegraphLayer, LineLayer, ArcLayer } from 'deck.gl';
import CubeiconLayer from '../cubeicon-layer';
import CubeGraphLayer from '../cubegraph-layer';
import PolygonIconLayer from '../polygon-icon-layer';
import { pickParams } from '../../library';
import { RoutePaths, MovedData, Movesbase, ClickedObject, Position, Radius, DataOption } from '../../types';
import * as Actions from '../../actions';
interface Props extends LayerProps {
    routePaths: RoutePaths[];
    layerRadiusScale?: number;
    layerOpacity?: number;
    movedData: MovedData[];
    movesbase: Movesbase[];
    clickedObject: null | ClickedObject[];
    actions: typeof Actions;
    optionVisible?: boolean;
    optionChange?: boolean;
    optionOpacity?: number;
    optionCellSize?: number;
    optionElevationScale?: number;
    iconChange?: boolean;
    iconCubeType?: number;
    iconCubeSize?: number;
    getColor?: (x: DataOption) => number[];
    getRadius?: (x: Radius) => number;
    getCubeColor?: (x: DataOption) => number[][];
    getCubeElevation?: (x: DataOption) => number[];
    getStrokeWidth?: any;
    scenegraph?: any;
    getOrientation?: (x: DataOption) => number[];
    getScale?: (x: DataOption) => number[];
    getTranslation?: (x: DataOption) => number[];
}
export default class MovesLayer extends CompositeLayer<Props> {
    constructor(props: Props);
    static defaultProps: {
        layerRadiusScale: number;
        layerOpacity: number;
        optionVisible: boolean;
        optionChange: boolean;
        optionOpacity: number;
        optionCellSize: number;
        optionElevationScale: number;
        visible: boolean;
        iconChange: boolean;
        iconCubeType: number;
        iconCubeSize: number;
        getColor: (x: DataOption) => number[];
        getRadius: (x: Radius) => number;
        getCubeColor: (x: DataOption) => number[] | number[][];
        getCubeElevation: (x: DataOption) => number[];
        getStrokeWidth: (x: any) => any;
        scenegraph: string;
        getOrientation: (x: any) => number[];
        getScale: number[];
        getTranslation: number[];
    };
    static layerName: string;
    getPickingInfo(pickParams: pickParams): void;
    renderLayers(): (CubeiconLayer | CubeGraphLayer | PolygonIconLayer | ScatterplotLayer<{
        id: string;
        data: MovedData[];
        radiusScale: number;
        getPosition: (x: Position) => number[];
        getFillColor: (x: DataOption) => number[];
        getRadius: (x: Radius) => number;
        visible: true;
        opacity: number;
        pickable: true;
        radiusMinPixels: number;
    }, {}> | ScenegraphLayer<{
        id: string;
        data: MovedData[];
        scenegraph: any;
        getPosition: (x: Position) => number[];
        getColor: (x: DataOption) => number[];
        getOrientation: (x: DataOption) => number[];
        getScale: (x: DataOption) => number[];
        getTranslation: (x: DataOption) => number[];
        visible: true;
        opacity: number;
        pickable: true;
    }, {}> | LineLayer<{
        id: string;
        data: RoutePaths[];
        widthUnits: string;
        getWidth: (x: any) => any;
        widthMinPixels: number;
        getColor: (x: DataOption) => number[];
        visible: true;
        pickable: false;
    }, {}> | ArcLayer<{
        id: string;
        data: any[];
        visible: true;
        pickable: true;
        widthUnits: string;
        widthMinPixels: number;
        getSourcePosition: (x: MovedData) => number[];
        getTargetPosition: (x: MovedData) => number[];
        getSourceColor: (x: MovedData) => (number | number[])[];
        getTargetColor: (x: MovedData) => (number | number[])[];
        getWidth: (x: any) => any;
        opacity: number;
    }, {}>)[];
}
export {};
